name = "calvarykaneohe"
compatibility_date = "2025-09-10"
compatibility_flags = ["nodejs_als", "nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"
observability = {
    "enabled": true
}

[[vars]]
IS_DEV = 'false'
NODE_MAILER_USERNAME='support@calvarykaneohe.church'

[[d1_databases]]
binding = "DB"
database_name = "calvary_content",
database_id = "b5a72b7a-2efd-4b64-94e0-2ac9fc362f32"
experimental_remote = true

[[secrets_store]]
"binding": "SECRET",
"store_id": "b25b58e5cff349ec9942e1598cd362b5",
"secret_name": "calvary_content_secret"