export default {
	componentHeight: 100,
	background_color_upper: '',
	background_color_lower: '',
	background_image_url: '',
	backgroundImageUrl: '/images/large-content-bg.webp',
	wideContent:
		'{"styled":{"ops":[{"attributes":{"color":"rgba(215, 195, 152, 0.89)"},"insert":"*** Personal Message and Prayer Request from Pastor JD - Updated July 17, 2025 ***"},{"attributes":{"align":"center","header":4},"insert":"\\n\\n"},{"attributes":{"color":"rgba(215, 195, 152, 0.89)","link":"/frequently-requested-resources"},"insert":"Go to Frequently Requested PDF Resources"},{"attributes":{"align":"center","header":4},"insert":"\\n"},{"attributes":{"align":"center"},"insert":"\\n"},{"attributes":{"color":"rgba(215, 195, 152, 0.89)"},"insert":"Please visit our "},{"attributes":{"color":"rgba(215, 195, 152, 0.89)","link":"/support-center"},"insert":"Support Center"},{"attributes":{"color":"rgba(215, 195, 152, 0.89)"},"insert":" for additional information, and assistance. "},{"attributes":{"align":"center","header":4},"insert":"\\n"}]},"html":"<h4 class=\\"ql-align-center\\"><span style=\\"color: rgba(215, 195, 152, 0.89);\\">*** Personal Message and Prayer Request from Pastor JD - Updated July 17, 2025 ***</span></h4><h4 class=\\"ql-align-center\\"></h4><h4 class=\\"ql-align-center\\"><a href=\\"/frequently-requested-resources\\" rel=\\"noopener noreferrer\\" target=\\"_blank\\" style=\\"color: rgba(215, 195, 152, 0.89);\\">Go to Frequently Requested PDF Resources</a></h4><p class=\\"ql-align-center\\"></p><h4 class=\\"ql-align-center\\"><span style=\\"color: rgba(215, 195, 152, 0.89);\\">Please visit our </span><a href=\\"/support-center\\" rel=\\"noopener noreferrer\\" target=\\"_blank\\" style=\\"color: rgba(215, 195, 152, 0.89);\\">Support Center</a><span style=\\"color: rgba(215, 195, 152, 0.89);\\"> for additional information, and assistance. </span></h4>"}',
	narrowContent:
		'{"styled":{"ops":[{"insert":"God in His Word has told us what\'s going to happen, before it happens, so when it begins to happen, non-believers will believe and believers will look up knowing our redemption draws near!"},{"attributes":{"header":3},"insert":"\\n"},{"insert":"JOHN 13:19 | JOHN 14:29 | LUKE 21:28"},{"attributes":{"align":"right","header":6},"insert":"\\n"}]},"html":"<h3>God in His Word has told us what&#39;s going to happen, before it happens, so when it begins to happen, non-believers will believe and believers will look up knowing our redemption draws near!</h3><h6 class=\\"ql-align-right\\">JOHN 13:19 | JOHN 14:29 | LUKE 21:28</h6>"}'
};
