export default {
	componentHeight: 20,
	backgroundImageUrl: '/images/large-content-bg.webp',
	mainImage: {
		href: '/prophecy-updates',
		url: '/images/JD_Snap_cover-p-1080.jpeg',
		alt: 'Watch On-demand Bible Prophecy Updates'
	},
	upperContent:
		'{"styled":{"ops":[{"attributes":{"color":"#c7a65e"},"insert":"*** Personal Message and Prayer Request from Pastor JD - Updated July 17, 2025 ***"},{"attributes":{"align":"center","header":4},"insert":"\\n\\n"},{"attributes":{"color":"#c7a65e","link":"/frequently-requested-resources"},"insert":"Go to Frequently Requested PDF Resources"},{"attributes":{"align":"center","header":4},"insert":"\\n"},{"attributes":{"align":"center"},"insert":"\\n"},{"attributes":{"color":"#c7a65e"},"insert":"Please visit our "},{"attributes":{"color":"#c7a65e","link":"/support-center"},"insert":"Support Center"},{"attributes":{"color":"#c7a65e"},"insert":" for additional information, and assistance."},{"attributes":{"align":"center","header":4},"insert":"\\n"}]},"html":"<h4 class=\\"ql-align-center\\"><span style=\\"color: rgb(199, 166, 94);\\">***&nbsp;Personal&nbsp;Message&nbsp;and&nbsp;Prayer&nbsp;Request&nbsp;from&nbsp;Pastor&nbsp;JD&nbsp;-&nbsp;Updated&nbsp;July&nbsp;17,&nbsp;2025&nbsp;***</span></h4><h4 class=\\"ql-align-center\\"></h4><h4 class=\\"ql-align-center\\"><a href=\\"/frequently-requested-resources\\" rel=\\"noopener noreferrer\\" target=\\"_blank\\" style=\\"color: rgb(199, 166, 94);\\">Go&nbsp;to&nbsp;Frequently&nbsp;Requested&nbsp;PDF&nbsp;Resources</a></h4><p class=\\"ql-align-center\\"></p><h4 class=\\"ql-align-center\\"><span style=\\"color: rgb(199, 166, 94);\\">Please&nbsp;visit&nbsp;our&nbsp;</span><a href=\\"/support-center\\" rel=\\"noopener noreferrer\\" target=\\"_blank\\" style=\\"color: rgb(199, 166, 94);\\">Support&nbsp;Center</a><span style=\\"color: rgb(199, 166, 94);\\">&nbsp;for&nbsp;additional&nbsp;information,&nbsp;and&nbsp;assistance.</span></h4>"}',
	lowerContent:
		'{"styled":{"ops":[{"insert":"God in His Word has told us what\'s going to happen, "},{"attributes":{"header":3},"insert":"\\n"},{"insert":"before it happens, so when it begins to happen, non-"},{"attributes":{"header":3},"insert":"\\n"},{"insert":"believers will believe and believers will look up knowing "},{"attributes":{"header":3},"insert":"\\n"},{"insert":"our redemption draws near!"},{"attributes":{"header":3},"insert":"\\n"},{"insert":"JOHN 13:19 | JOHN 14:29 | LUKE 21:28"},{"attributes":{"align":"right","header":6},"insert":"\\n"}]},"html":"<h3>God&nbsp;in&nbsp;His&nbsp;Word&nbsp;has&nbsp;told&nbsp;us&nbsp;what&#39;s&nbsp;going&nbsp;to&nbsp;happen,&nbsp;</h3><h3>before&nbsp;it&nbsp;happens,&nbsp;so&nbsp;when&nbsp;it&nbsp;begins&nbsp;to&nbsp;happen,&nbsp;non-</h3><h3>believers&nbsp;will&nbsp;believe&nbsp;and&nbsp;believers&nbsp;will&nbsp;look&nbsp;up&nbsp;knowing&nbsp;</h3><h3>our&nbsp;redemption&nbsp;draws&nbsp;near!</h3><h6 class=\\"ql-align-right\\">JOHN&nbsp;13:19&nbsp;|&nbsp;JOHN&nbsp;14:29&nbsp;|&nbsp;LUKE&nbsp;21:28</h6>"}'
};
