export default [
	{ value: 'transparent', label: 'Transparent' },
	{ value: '#24211c', label: 'Darkness' },
	{ value: '#271254cc', label: 'Deep Purple' },
	{ value: '#29213acc', label: 'Midnight Royal' },
	{ value: '#666666', label: 'Dim Grey' },
	{ value: '#f2eee5', label: 'Floral White' },
	{ value: 'whitesmoke', label: 'White Smoke' },
	{ value: '#ed484bcc', label: 'Indian Red' },
	{ value: 'white', label: 'White' },
	{ value: '#725414', label: 'Dark Gold' },
	{ value: '#c7a65e', label: 'Burlywood' },
	{ value: '#82621f', label: 'Gold' },
	{ value: '#d2cbbb', label: 'Khaki' },
	{ value: '#d3cdc0', label: 'Khaki 2' },
	{ value: '#201c29f7', label: 'Dark Purple' },
	{ value: '#333', label: 'Dark Grey' },
	{ value: '#29213aa8', label: 'Midnight Blue' },
	{ value: '#d7c398e3', label: 'Tan' },
	{ value: '#dfdfdf', label: 'Gainsboro' },
	{ value: '#f5f5f536', label: 'White Transparent' },
	{ value: '#333c', label: 'Trans Dark' },
	{ value: '#251f33f2', label: 'Passion' },
	{ value: '#24211ccc', label: 'Black Trans' }
];
